name: Build Mods Zip

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Create zip
        run: zip -r mods.zip mods/

      - name: Create tag
        run: |
          TAG=v$(date +'%Y%m%d-%H%M')
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: mods.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
